apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-http-trigger
  labels:
    app: blob-http-trigger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob-http-trigger
  template:
    metadata:
      labels:
        app: blob-http-trigger
    spec:
      containers:
      - name: blob-http-trigger
        image: jmlcoliveira/blob-http-trigger:latest
        ports:
        - containerPort: 8080
        env:
        - name: SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: db-user-secret
              key: SECRET_TOKEN
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: db-user-secret
              key: POSTGRES_URL
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-user-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-secret
              key: POSTGRES_PASSWORD
        - name: REDIS_HOSTNAME
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: blob-http-trigger-service
spec:
  selector:
    app: blob-http-trigger
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP