apiVersion: batch/v1
kind: Job
metadata:
  name: create-db-user
spec:
  template:
    spec:
      containers:
      - name: create-db-user
        image: postgres:17
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-user-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-secret
              key: DB_PASSWORD
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_DB
          value: "postgres-scc-2425"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-user-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-secret
              key: POSTGRES_PASSWORD
        command: ["bash", "-c"]
        args:
        - |
          PGPASSWORD=$POSTGRES_PASSWORD psql -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
            DO
            \$\$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$DB_USER') THEN
                    CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';
                END IF;
            END
            \$\$
            ;
          EOSQL
      restartPolicy: OnFailure