apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-user-secret
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-secret
              key: DB_PASSWORD
        - name: POSTGRES_DB
          value: "postgres-scc-2425"
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: db-init-scripts
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: db-init-scripts
        configMap:
          name: db-init-scripts
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres