apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc2425-webapp
  labels:
    app: scc2425-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scc2425-webapp
  template:
    metadata:
      labels:
        app: scc2425-webapp
    spec:
      containers:
      - name: scc2425-webapp
        image: jmlcoliveira/scc2425-webapp:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: media-volume
          mountPath: /data/media
        env:
        - name: BLOB_PATH
          value: /data/media
        - name: REDIS_HOSTNAME
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-user-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-secret
              key: DB_PASSWORD
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: scc2425-webapp-service
spec:
  selector:
    app: scc2425-webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer